; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-dev]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_cpu = 160000000L
lib_deps = 
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2
	paulstoffregen/OneWire@^2.3.7
	milesburton/DallasTemperature@^3.11.0
	bogde/HX711@^0.7.5

build_flags = 
	-D CORE_DEBUG_LEVEL=0
	-D CONFIG_ESP32_DEEP_SLEEP_WAKEUP_DELAY=2000

; === РЕЖИМ USB ПРОШИВКИ (для первой прошивки) ===
upload_protocol = esptool
upload_port = /dev/ttyUSB0  ; для Linux (или COM3 для Windows)


; === РЕЖИМ ПРОШИВКИ OTA (после первой прошивки) ===
; upload_protocol = espota
; upload_port = esp-hive.local
; upload_flags = 
;	--port=3232
;	--auth=100500